//Modern metals & base metals remove all tools


// NOTE!! CRACKHAMMER NOT REMOVED BECAUSE IT's UNIQUE TO THE MOD
// armour, horse armour, shears not removed



//Pickaxes
recipes.remove(<modernmetals:aluminum_pickaxe>);
recipes.remove(<modernmetals:aluminumbrass_pickaxe>);
recipes.remove(<modernmetals:cadmium_pickaxe>);
recipes.remove(<modernmetals:chromium_pickaxe>);
recipes.remove(<modernmetals:galvanizedsteel_pickaxe>);
recipes.remove(<modernmetals:iridium_pickaxe>);
recipes.remove(<modernmetals:magnesium_pickaxe>);
recipes.remove(<modernmetals:manganese_pickaxe>);
recipes.remove(<modernmetals:nichrome_pickaxe>);
recipes.remove(<modernmetals:osmium_pickaxe>);
recipes.remove(<modernmetals:plutonium_pickaxe>);
recipes.remove(<modernmetals:rutile_pickaxe>);
recipes.remove(<modernmetals:stainlesssteel_pickaxe>);
recipes.remove(<modernmetals:tantalum_pickaxe>);
recipes.remove(<modernmetals:titanium_pickaxe>);
recipes.remove(<modernmetals:tungsten_pickaxe>);
recipes.remove(<modernmetals:uranium_pickaxe>);
recipes.remove(<modernmetals:zirconium_pickaxe>);

recipes.remove(<basemetals:adamantine_pickaxe>);
recipes.remove(<basemetals:aquarium_pickaxe>);
recipes.remove(<basemetals:brass_pickaxe>);
recipes.remove(<basemetals:bronze_pickaxe>);
recipes.remove(<basemetals:coldiron_pickaxe>);
recipes.remove(<basemetals:copper_pickaxe>);
recipes.remove(<basemetals:cupronickel_pickaxe>);
recipes.remove(<basemetals:electrum_pickaxe>);
recipes.remove(<basemetals:invar_pickaxe>);
recipes.remove(<basemetals:lead_pickaxe>);
recipes.remove(<basemetals:mithril_pickaxe>);
recipes.remove(<basemetals:nickel_pickaxe>);
recipes.remove(<basemetals:platinum_pickaxe>);
recipes.remove(<basemetals:silver_pickaxe>);
recipes.remove(<basemetals:starsteel_pickaxe>);
recipes.remove(<basemetals:steel_pickaxe>);
recipes.remove(<basemetals:tin_pickaxe>);

mods.jei.JEI.hide(<modernmetals:aluminum_pickaxe>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_pickaxe>);
mods.jei.JEI.hide(<modernmetals:cadmium_pickaxe>);
mods.jei.JEI.hide(<modernmetals:chromium_pickaxe>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_pickaxe>);
mods.jei.JEI.hide(<modernmetals:iridium_pickaxe>);
mods.jei.JEI.hide(<modernmetals:magnesium_pickaxe>);
mods.jei.JEI.hide(<modernmetals:manganese_pickaxe>);
mods.jei.JEI.hide(<modernmetals:nichrome_pickaxe>);
mods.jei.JEI.hide(<modernmetals:osmium_pickaxe>);
mods.jei.JEI.hide(<modernmetals:plutonium_pickaxe>);
mods.jei.JEI.hide(<modernmetals:rutile_pickaxe>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_pickaxe>);
mods.jei.JEI.hide(<modernmetals:tantalum_pickaxe>);
mods.jei.JEI.hide(<modernmetals:titanium_pickaxe>);
mods.jei.JEI.hide(<modernmetals:tungsten_pickaxe>);
mods.jei.JEI.hide(<modernmetals:uranium_pickaxe>);
mods.jei.JEI.hide(<modernmetals:zirconium_pickaxe>);

mods.jei.JEI.hide(<basemetals:adamantine_pickaxe>);
mods.jei.JEI.hide(<basemetals:aquarium_pickaxe>);
mods.jei.JEI.hide(<basemetals:brass_pickaxe>);
mods.jei.JEI.hide(<basemetals:bronze_pickaxe>);
mods.jei.JEI.hide(<basemetals:coldiron_pickaxe>);
mods.jei.JEI.hide(<basemetals:copper_pickaxe>);
mods.jei.JEI.hide(<basemetals:cupronickel_pickaxe>);
mods.jei.JEI.hide(<basemetals:electrum_pickaxe>);
mods.jei.JEI.hide(<basemetals:invar_pickaxe>);
mods.jei.JEI.hide(<basemetals:lead_pickaxe>);
mods.jei.JEI.hide(<basemetals:mithril_pickaxe>);
mods.jei.JEI.hide(<basemetals:nickel_pickaxe>);
mods.jei.JEI.hide(<basemetals:platinum_pickaxe>);
mods.jei.JEI.hide(<basemetals:silver_pickaxe>);
mods.jei.JEI.hide(<basemetals:starsteel_pickaxe>);
mods.jei.JEI.hide(<basemetals:steel_pickaxe>);
mods.jei.JEI.hide(<basemetals:tin_pickaxe>);



//Shovels
recipes.remove(<modernmetals:aluminum_shovel>);
recipes.remove(<modernmetals:aluminumbrass_shovel>);
recipes.remove(<modernmetals:cadmium_shovel>);
recipes.remove(<modernmetals:chromium_shovel>);
recipes.remove(<modernmetals:galvanizedsteel_shovel>);
recipes.remove(<modernmetals:iridium_shovel>);
recipes.remove(<modernmetals:magnesium_shovel>);
recipes.remove(<modernmetals:manganese_shovel>);
recipes.remove(<modernmetals:nichrome_shovel>);
recipes.remove(<modernmetals:osmium_shovel>);
recipes.remove(<modernmetals:plutonium_shovel>);
recipes.remove(<modernmetals:rutile_shovel>);
recipes.remove(<modernmetals:stainlesssteel_shovel>);
recipes.remove(<modernmetals:tantalum_shovel>);
recipes.remove(<modernmetals:titanium_shovel>);
recipes.remove(<modernmetals:tungsten_shovel>);
recipes.remove(<modernmetals:uranium_shovel>);
recipes.remove(<modernmetals:zirconium_shovel>);

recipes.remove(<basemetals:adamantine_shovel>);
recipes.remove(<basemetals:aquarium_shovel>);
recipes.remove(<basemetals:brass_shovel>);
recipes.remove(<basemetals:bronze_shovel>);
recipes.remove(<basemetals:coldiron_shovel>);
recipes.remove(<basemetals:copper_shovel>);
recipes.remove(<basemetals:cupronickel_shovel>);
recipes.remove(<basemetals:electrum_shovel>);
recipes.remove(<basemetals:invar_shovel>);
recipes.remove(<basemetals:lead_shovel>);
recipes.remove(<basemetals:mithril_shovel>);
recipes.remove(<basemetals:nickel_shovel>);
recipes.remove(<basemetals:platinum_shovel>);
recipes.remove(<basemetals:silver_shovel>);
recipes.remove(<basemetals:starsteel_shovel>);
recipes.remove(<basemetals:steel_shovel>);
recipes.remove(<basemetals:tin_shovel>);

mods.jei.JEI.hide(<modernmetals:aluminum_shovel>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_shovel>);
mods.jei.JEI.hide(<modernmetals:cadmium_shovel>);
mods.jei.JEI.hide(<modernmetals:chromium_shovel>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_shovel>);
mods.jei.JEI.hide(<modernmetals:iridium_shovel>);
mods.jei.JEI.hide(<modernmetals:magnesium_shovel>);
mods.jei.JEI.hide(<modernmetals:manganese_shovel>);
mods.jei.JEI.hide(<modernmetals:nichrome_shovel>);
mods.jei.JEI.hide(<modernmetals:osmium_shovel>);
mods.jei.JEI.hide(<modernmetals:plutonium_shovel>);
mods.jei.JEI.hide(<modernmetals:rutile_shovel>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_shovel>);
mods.jei.JEI.hide(<modernmetals:tantalum_shovel>);
mods.jei.JEI.hide(<modernmetals:titanium_shovel>);
mods.jei.JEI.hide(<modernmetals:tungsten_shovel>);
mods.jei.JEI.hide(<modernmetals:uranium_shovel>);
mods.jei.JEI.hide(<modernmetals:zirconium_shovel>);

mods.jei.JEI.hide(<basemetals:adamantine_shovel>);
mods.jei.JEI.hide(<basemetals:aquarium_shovel>);
mods.jei.JEI.hide(<basemetals:brass_shovel>);
mods.jei.JEI.hide(<basemetals:bronze_shovel>);
mods.jei.JEI.hide(<basemetals:coldiron_shovel>);
mods.jei.JEI.hide(<basemetals:copper_shovel>);
mods.jei.JEI.hide(<basemetals:cupronickel_shovel>);
mods.jei.JEI.hide(<basemetals:electrum_shovel>);
mods.jei.JEI.hide(<basemetals:invar_shovel>);
mods.jei.JEI.hide(<basemetals:lead_shovel>);
mods.jei.JEI.hide(<basemetals:mithril_shovel>);
mods.jei.JEI.hide(<basemetals:nickel_shovel>);
mods.jei.JEI.hide(<basemetals:platinum_shovel>);
mods.jei.JEI.hide(<basemetals:silver_shovel>);
mods.jei.JEI.hide(<basemetals:starsteel_shovel>);
mods.jei.JEI.hide(<basemetals:steel_shovel>);
mods.jei.JEI.hide(<basemetals:tin_shovel>);



//Axes
recipes.remove(<modernmetals:aluminum_axe>);
recipes.remove(<modernmetals:aluminumbrass_axe>);
recipes.remove(<modernmetals:cadmium_axe>);
recipes.remove(<modernmetals:chromium_axe>);
recipes.remove(<modernmetals:galvanizedsteel_axe>);
recipes.remove(<modernmetals:iridium_axe>);
recipes.remove(<modernmetals:magnesium_axe>);
recipes.remove(<modernmetals:manganese_axe>);
recipes.remove(<modernmetals:nichrome_axe>);
recipes.remove(<modernmetals:osmium_axe>);
recipes.remove(<modernmetals:plutonium_axe>);
recipes.remove(<modernmetals:rutile_axe>);
recipes.remove(<modernmetals:stainlesssteel_axe>);
recipes.remove(<modernmetals:tantalum_axe>);
recipes.remove(<modernmetals:titanium_axe>);
recipes.remove(<modernmetals:tungsten_axe>);
recipes.remove(<modernmetals:uranium_axe>);
recipes.remove(<modernmetals:zirconium_axe>);

recipes.remove(<basemetals:adamantine_axe>);
recipes.remove(<basemetals:aquarium_axe>);
recipes.remove(<basemetals:brass_axe>);
recipes.remove(<basemetals:bronze_axe>);
recipes.remove(<basemetals:coldiron_axe>);
recipes.remove(<basemetals:copper_axe>);
recipes.remove(<basemetals:cupronickel_axe>);
recipes.remove(<basemetals:electrum_axe>);
recipes.remove(<basemetals:invar_axe>);
recipes.remove(<basemetals:lead_axe>);
recipes.remove(<basemetals:mithril_axe>);
recipes.remove(<basemetals:nickel_axe>);
recipes.remove(<basemetals:platinum_axe>);
recipes.remove(<basemetals:silver_axe>);
recipes.remove(<basemetals:starsteel_axe>);
recipes.remove(<basemetals:steel_axe>);
recipes.remove(<basemetals:tin_axe>);

mods.jei.JEI.hide(<modernmetals:aluminum_axe>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_axe>);
mods.jei.JEI.hide(<modernmetals:cadmium_axe>);
mods.jei.JEI.hide(<modernmetals:chromium_axe>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_axe>);
mods.jei.JEI.hide(<modernmetals:iridium_axe>);
mods.jei.JEI.hide(<modernmetals:magnesium_axe>);
mods.jei.JEI.hide(<modernmetals:manganese_axe>);
mods.jei.JEI.hide(<modernmetals:nichrome_axe>);
mods.jei.JEI.hide(<modernmetals:osmium_axe>);
mods.jei.JEI.hide(<modernmetals:plutonium_axe>);
mods.jei.JEI.hide(<modernmetals:rutile_axe>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_axe>);
mods.jei.JEI.hide(<modernmetals:tantalum_axe>);
mods.jei.JEI.hide(<modernmetals:titanium_axe>);
mods.jei.JEI.hide(<modernmetals:tungsten_axe>);
mods.jei.JEI.hide(<modernmetals:uranium_axe>);
mods.jei.JEI.hide(<modernmetals:zirconium_axe>);

mods.jei.JEI.hide(<basemetals:adamantine_axe>);
mods.jei.JEI.hide(<basemetals:aquarium_axe>);
mods.jei.JEI.hide(<basemetals:brass_axe>);
mods.jei.JEI.hide(<basemetals:bronze_axe>);
mods.jei.JEI.hide(<basemetals:coldiron_axe>);
mods.jei.JEI.hide(<basemetals:copper_axe>);
mods.jei.JEI.hide(<basemetals:cupronickel_axe>);
mods.jei.JEI.hide(<basemetals:electrum_axe>);
mods.jei.JEI.hide(<basemetals:invar_axe>);
mods.jei.JEI.hide(<basemetals:lead_axe>);
mods.jei.JEI.hide(<basemetals:mithril_axe>);
mods.jei.JEI.hide(<basemetals:nickel_axe>);
mods.jei.JEI.hide(<basemetals:platinum_axe>);
mods.jei.JEI.hide(<basemetals:silver_axe>);
mods.jei.JEI.hide(<basemetals:starsteel_axe>);
mods.jei.JEI.hide(<basemetals:steel_axe>);
mods.jei.JEI.hide(<basemetals:tin_axe>);



//hoes
recipes.remove(<modernmetals:aluminum_hoe>);
recipes.remove(<modernmetals:aluminumbrass_hoe>);
recipes.remove(<modernmetals:cadmium_hoe>);
recipes.remove(<modernmetals:chromium_hoe>);
recipes.remove(<modernmetals:galvanizedsteel_hoe>);
recipes.remove(<modernmetals:iridium_hoe>);
recipes.remove(<modernmetals:magnesium_hoe>);
recipes.remove(<modernmetals:manganese_hoe>);
recipes.remove(<modernmetals:nichrome_hoe>);
recipes.remove(<modernmetals:osmium_hoe>);
recipes.remove(<modernmetals:plutonium_hoe>);
recipes.remove(<modernmetals:rutile_hoe>);
recipes.remove(<modernmetals:stainlesssteel_hoe>);
recipes.remove(<modernmetals:tantalum_hoe>);
recipes.remove(<modernmetals:titanium_hoe>);
recipes.remove(<modernmetals:tungsten_hoe>);
recipes.remove(<modernmetals:uranium_hoe>);
recipes.remove(<modernmetals:zirconium_hoe>);

recipes.remove(<basemetals:adamantine_hoe>);
recipes.remove(<basemetals:aquarium_hoe>);
recipes.remove(<basemetals:brass_hoe>);
recipes.remove(<basemetals:bronze_hoe>);
recipes.remove(<basemetals:coldiron_hoe>);
recipes.remove(<basemetals:copper_hoe>);
recipes.remove(<basemetals:cupronickel_hoe>);
recipes.remove(<basemetals:electrum_hoe>);
recipes.remove(<basemetals:invar_hoe>);
recipes.remove(<basemetals:lead_hoe>);
recipes.remove(<basemetals:mithril_hoe>);
recipes.remove(<basemetals:nickel_hoe>);
recipes.remove(<basemetals:platinum_hoe>);
recipes.remove(<basemetals:silver_hoe>);
recipes.remove(<basemetals:starsteel_hoe>);
recipes.remove(<basemetals:steel_hoe>);
recipes.remove(<basemetals:tin_hoe>);

mods.jei.JEI.hide(<modernmetals:aluminum_hoe>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_hoe>);
mods.jei.JEI.hide(<modernmetals:cadmium_hoe>);
mods.jei.JEI.hide(<modernmetals:chromium_hoe>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_hoe>);
mods.jei.JEI.hide(<modernmetals:iridium_hoe>);
mods.jei.JEI.hide(<modernmetals:magnesium_hoe>);
mods.jei.JEI.hide(<modernmetals:manganese_hoe>);
mods.jei.JEI.hide(<modernmetals:nichrome_hoe>);
mods.jei.JEI.hide(<modernmetals:osmium_hoe>);
mods.jei.JEI.hide(<modernmetals:plutonium_hoe>);
mods.jei.JEI.hide(<modernmetals:rutile_hoe>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_hoe>);
mods.jei.JEI.hide(<modernmetals:tantalum_hoe>);
mods.jei.JEI.hide(<modernmetals:titanium_hoe>);
mods.jei.JEI.hide(<modernmetals:tungsten_hoe>);
mods.jei.JEI.hide(<modernmetals:uranium_hoe>);
mods.jei.JEI.hide(<modernmetals:zirconium_hoe>);

mods.jei.JEI.hide(<basemetals:adamantine_hoe>);
mods.jei.JEI.hide(<basemetals:aquarium_hoe>);
mods.jei.JEI.hide(<basemetals:brass_hoe>);
mods.jei.JEI.hide(<basemetals:bronze_hoe>);
mods.jei.JEI.hide(<basemetals:coldiron_hoe>);
mods.jei.JEI.hide(<basemetals:copper_hoe>);
mods.jei.JEI.hide(<basemetals:cupronickel_hoe>);
mods.jei.JEI.hide(<basemetals:electrum_hoe>);
mods.jei.JEI.hide(<basemetals:invar_hoe>);
mods.jei.JEI.hide(<basemetals:lead_hoe>);
mods.jei.JEI.hide(<basemetals:mithril_hoe>);
mods.jei.JEI.hide(<basemetals:nickel_hoe>);
mods.jei.JEI.hide(<basemetals:platinum_hoe>);
mods.jei.JEI.hide(<basemetals:silver_hoe>);
mods.jei.JEI.hide(<basemetals:starsteel_hoe>);
mods.jei.JEI.hide(<basemetals:steel_hoe>);
mods.jei.JEI.hide(<basemetals:tin_hoe>);



//swords
recipes.remove(<modernmetals:aluminum_sword>);
recipes.remove(<modernmetals:aluminumbrass_sword>);
recipes.remove(<modernmetals:cadmium_sword>);
recipes.remove(<modernmetals:chromium_sword>);
recipes.remove(<modernmetals:galvanizedsteel_sword>);
recipes.remove(<modernmetals:iridium_sword>);
recipes.remove(<modernmetals:magnesium_sword>);
recipes.remove(<modernmetals:manganese_sword>);
recipes.remove(<modernmetals:nichrome_sword>);
recipes.remove(<modernmetals:osmium_sword>);
recipes.remove(<modernmetals:plutonium_sword>);
recipes.remove(<modernmetals:rutile_sword>);
recipes.remove(<modernmetals:stainlesssteel_sword>);
recipes.remove(<modernmetals:tantalum_sword>);
recipes.remove(<modernmetals:titanium_sword>);
recipes.remove(<modernmetals:tungsten_sword>);
recipes.remove(<modernmetals:uranium_sword>);
recipes.remove(<modernmetals:zirconium_sword>);

recipes.remove(<basemetals:adamantine_sword>);
recipes.remove(<basemetals:aquarium_sword>);
recipes.remove(<basemetals:brass_sword>);
recipes.remove(<basemetals:bronze_sword>);
recipes.remove(<basemetals:coldiron_sword>);
recipes.remove(<basemetals:copper_sword>);
recipes.remove(<basemetals:cupronickel_sword>);
recipes.remove(<basemetals:electrum_sword>);
recipes.remove(<basemetals:invar_sword>);
recipes.remove(<basemetals:lead_sword>);
recipes.remove(<basemetals:mithril_sword>);
recipes.remove(<basemetals:nickel_sword>);
recipes.remove(<basemetals:platinum_sword>);
recipes.remove(<basemetals:silver_sword>);
recipes.remove(<basemetals:starsteel_sword>);
recipes.remove(<basemetals:steel_sword>);
recipes.remove(<basemetals:tin_sword>);

mods.jei.JEI.hide(<modernmetals:aluminum_sword>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_sword>);
mods.jei.JEI.hide(<modernmetals:cadmium_sword>);
mods.jei.JEI.hide(<modernmetals:chromium_sword>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_sword>);
mods.jei.JEI.hide(<modernmetals:iridium_sword>);
mods.jei.JEI.hide(<modernmetals:magnesium_sword>);
mods.jei.JEI.hide(<modernmetals:manganese_sword>);
mods.jei.JEI.hide(<modernmetals:nichrome_sword>);
mods.jei.JEI.hide(<modernmetals:osmium_sword>);
mods.jei.JEI.hide(<modernmetals:plutonium_sword>);
mods.jei.JEI.hide(<modernmetals:rutile_sword>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_sword>);
mods.jei.JEI.hide(<modernmetals:tantalum_sword>);
mods.jei.JEI.hide(<modernmetals:titanium_sword>);
mods.jei.JEI.hide(<modernmetals:tungsten_sword>);
mods.jei.JEI.hide(<modernmetals:uranium_sword>);
mods.jei.JEI.hide(<modernmetals:zirconium_sword>);

mods.jei.JEI.hide(<basemetals:adamantine_sword>);
mods.jei.JEI.hide(<basemetals:aquarium_sword>);
mods.jei.JEI.hide(<basemetals:brass_sword>);
mods.jei.JEI.hide(<basemetals:bronze_sword>);
mods.jei.JEI.hide(<basemetals:coldiron_sword>);
mods.jei.JEI.hide(<basemetals:copper_sword>);
mods.jei.JEI.hide(<basemetals:cupronickel_sword>);
mods.jei.JEI.hide(<basemetals:electrum_sword>);
mods.jei.JEI.hide(<basemetals:invar_sword>);
mods.jei.JEI.hide(<basemetals:lead_sword>);
mods.jei.JEI.hide(<basemetals:mithril_sword>);
mods.jei.JEI.hide(<basemetals:nickel_sword>);
mods.jei.JEI.hide(<basemetals:platinum_sword>);
mods.jei.JEI.hide(<basemetals:silver_sword>);
mods.jei.JEI.hide(<basemetals:starsteel_sword>);
mods.jei.JEI.hide(<basemetals:steel_sword>);
mods.jei.JEI.hide(<basemetals:tin_sword>);



//doors
recipes.remove(<modernmetals:aluminum_door_item>);
recipes.remove(<modernmetals:aluminumbrass_door_item>);
recipes.remove(<modernmetals:cadmium_door_item>);
recipes.remove(<modernmetals:chromium_door_item>);
recipes.remove(<modernmetals:galvanizedsteel_door_item>);
recipes.remove(<modernmetals:iridium_door_item>);
recipes.remove(<modernmetals:magnesium_door_item>);
recipes.remove(<modernmetals:manganese_door_item>);
recipes.remove(<modernmetals:nichrome_door_item>);
recipes.remove(<modernmetals:osmium_door_item>);
recipes.remove(<modernmetals:plutonium_door_item>);
recipes.remove(<modernmetals:rutile_door_item>);
recipes.remove(<modernmetals:stainlesssteel_door_item>);
recipes.remove(<modernmetals:tantalum_door_item>);
recipes.remove(<modernmetals:titanium_door_item>);
recipes.remove(<modernmetals:tungsten_door_item>);
recipes.remove(<modernmetals:uranium_door_item>);
recipes.remove(<modernmetals:zirconium_door_item>);

recipes.remove(<basemetals:adamantine_door_item>);
recipes.remove(<basemetals:aquarium_door_item>);
recipes.remove(<basemetals:brass_door_item>);
recipes.remove(<basemetals:bronze_door_item>);
recipes.remove(<basemetals:coldiron_door_item>);
recipes.remove(<basemetals:copper_door_item>);
recipes.remove(<basemetals:cupronickel_door_item>);
recipes.remove(<basemetals:electrum_door_item>);
recipes.remove(<basemetals:invar_door_item>);
recipes.remove(<basemetals:lead_door_item>);
recipes.remove(<basemetals:mithril_door_item>);
recipes.remove(<basemetals:nickel_door_item>);
recipes.remove(<basemetals:platinum_door_item>);
recipes.remove(<basemetals:silver_door_item>);
recipes.remove(<basemetals:starsteel_door_item>);
recipes.remove(<basemetals:steel_door_item>);
recipes.remove(<basemetals:tin_door_item>);

mods.jei.JEI.hide(<modernmetals:aluminum_door_item>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_door_item>);
mods.jei.JEI.hide(<modernmetals:cadmium_door_item>);
mods.jei.JEI.hide(<modernmetals:chromium_door_item>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_door_item>);
mods.jei.JEI.hide(<modernmetals:iridium_door_item>);
mods.jei.JEI.hide(<modernmetals:magnesium_door_item>);
mods.jei.JEI.hide(<modernmetals:manganese_door_item>);
mods.jei.JEI.hide(<modernmetals:nichrome_door_item>);
mods.jei.JEI.hide(<modernmetals:osmium_door_item>);
mods.jei.JEI.hide(<modernmetals:plutonium_door_item>);
mods.jei.JEI.hide(<modernmetals:rutile_door_item>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_door_item>);
mods.jei.JEI.hide(<modernmetals:tantalum_door_item>);
mods.jei.JEI.hide(<modernmetals:titanium_door_item>);
mods.jei.JEI.hide(<modernmetals:tungsten_door_item>);
mods.jei.JEI.hide(<modernmetals:uranium_door_item>);
mods.jei.JEI.hide(<modernmetals:zirconium_door_item>);

mods.jei.JEI.hide(<basemetals:adamantine_door_item>);
mods.jei.JEI.hide(<basemetals:aquarium_door_item>);
mods.jei.JEI.hide(<basemetals:brass_door_item>);
mods.jei.JEI.hide(<basemetals:bronze_door_item>);
mods.jei.JEI.hide(<basemetals:coldiron_door_item>);
mods.jei.JEI.hide(<basemetals:copper_door_item>);
mods.jei.JEI.hide(<basemetals:cupronickel_door_item>);
mods.jei.JEI.hide(<basemetals:electrum_door_item>);
mods.jei.JEI.hide(<basemetals:invar_door_item>);
mods.jei.JEI.hide(<basemetals:lead_door_item>);
mods.jei.JEI.hide(<basemetals:mithril_door_item>);
mods.jei.JEI.hide(<basemetals:nickel_door_item>);
mods.jei.JEI.hide(<basemetals:platinum_door_item>);
mods.jei.JEI.hide(<basemetals:silver_door_item>);
mods.jei.JEI.hide(<basemetals:starsteel_door_item>);
mods.jei.JEI.hide(<basemetals:steel_door_item>);
mods.jei.JEI.hide(<basemetals:tin_door_item>);



// Trapdoors
recipes.remove(<modernmetals:aluminum_trapdoor>);
recipes.remove(<modernmetals:aluminumbrass_trapdoor>);
recipes.remove(<modernmetals:cadmium_trapdoor>);
recipes.remove(<modernmetals:chromium_trapdoor>);
recipes.remove(<modernmetals:galvanizedsteel_trapdoor>);
recipes.remove(<modernmetals:iridium_trapdoor>);
recipes.remove(<modernmetals:magnesium_trapdoor>);
recipes.remove(<modernmetals:manganese_trapdoor>);
recipes.remove(<modernmetals:nichrome_trapdoor>);
recipes.remove(<modernmetals:osmium_trapdoor>);
recipes.remove(<modernmetals:plutonium_trapdoor>);
recipes.remove(<modernmetals:rutile_trapdoor>);
recipes.remove(<modernmetals:stainlesssteel_trapdoor>);
recipes.remove(<modernmetals:tantalum_trapdoor>);
recipes.remove(<modernmetals:titanium_trapdoor>);
recipes.remove(<modernmetals:tungsten_trapdoor>);
recipes.remove(<modernmetals:uranium_trapdoor>);
recipes.remove(<modernmetals:zirconium_trapdoor>);

recipes.remove(<basemetals:adamantine_trapdoor>);
recipes.remove(<basemetals:aquarium_trapdoor>);
recipes.remove(<basemetals:brass_trapdoor>);
recipes.remove(<basemetals:bronze_trapdoor>);
recipes.remove(<basemetals:coldiron_trapdoor>);
recipes.remove(<basemetals:copper_trapdoor>);
recipes.remove(<basemetals:cupronickel_trapdoor>);
recipes.remove(<basemetals:electrum_trapdoor>);
recipes.remove(<basemetals:invar_trapdoor>);
recipes.remove(<basemetals:lead_trapdoor>);
recipes.remove(<basemetals:mithril_trapdoor>);
recipes.remove(<basemetals:nickel_trapdoor>);
recipes.remove(<basemetals:platinum_trapdoor>);
recipes.remove(<basemetals:silver_trapdoor>);
recipes.remove(<basemetals:starsteel_trapdoor>);
recipes.remove(<basemetals:steel_trapdoor>);
recipes.remove(<basemetals:tin_trapdoor>);


mods.jei.JEI.hide(<modernmetals:aluminum_trapdoor>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_trapdoor>);
mods.jei.JEI.hide(<modernmetals:cadmium_trapdoor>);
mods.jei.JEI.hide(<modernmetals:chromium_trapdoor>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_trapdoor>);
mods.jei.JEI.hide(<modernmetals:iridium_trapdoor>);
mods.jei.JEI.hide(<modernmetals:magnesium_trapdoor>);
mods.jei.JEI.hide(<modernmetals:manganese_trapdoor>);
mods.jei.JEI.hide(<modernmetals:nichrome_trapdoor>);
mods.jei.JEI.hide(<modernmetals:osmium_trapdoor>);
mods.jei.JEI.hide(<modernmetals:plutonium_trapdoor>);
mods.jei.JEI.hide(<modernmetals:rutile_trapdoor>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_trapdoor>);
mods.jei.JEI.hide(<modernmetals:tantalum_trapdoor>);
mods.jei.JEI.hide(<modernmetals:titanium_trapdoor>);
mods.jei.JEI.hide(<modernmetals:tungsten_trapdoor>);
mods.jei.JEI.hide(<modernmetals:uranium_trapdoor>);
mods.jei.JEI.hide(<modernmetals:zirconium_trapdoor>);

mods.jei.JEI.hide(<basemetals:adamantine_trapdoor>);
mods.jei.JEI.hide(<basemetals:aquarium_trapdoor>);
mods.jei.JEI.hide(<basemetals:brass_trapdoor>);
mods.jei.JEI.hide(<basemetals:bronze_trapdoor>);
mods.jei.JEI.hide(<basemetals:coldiron_trapdoor>);
mods.jei.JEI.hide(<basemetals:copper_trapdoor>);
mods.jei.JEI.hide(<basemetals:cupronickel_trapdoor>);
mods.jei.JEI.hide(<basemetals:electrum_trapdoor>);
mods.jei.JEI.hide(<basemetals:invar_trapdoor>);
mods.jei.JEI.hide(<basemetals:lead_trapdoor>);
mods.jei.JEI.hide(<basemetals:mithril_trapdoor>);
mods.jei.JEI.hide(<basemetals:nickel_trapdoor>);
mods.jei.JEI.hide(<basemetals:platinum_trapdoor>);
mods.jei.JEI.hide(<basemetals:silver_trapdoor>);
mods.jei.JEI.hide(<basemetals:starsteel_trapdoor>);
mods.jei.JEI.hide(<basemetals:steel_trapdoor>);
mods.jei.JEI.hide(<basemetals:tin_trapdoor>);



// bows
recipes.remove(<modernmetals:aluminum_bow>);
recipes.remove(<modernmetals:aluminumbrass_bow>);
recipes.remove(<modernmetals:cadmium_bow>);
recipes.remove(<modernmetals:chromium_bow>);
recipes.remove(<modernmetals:galvanizedsteel_bow>);
recipes.remove(<modernmetals:iridium_bow>);
recipes.remove(<modernmetals:magnesium_bow>);
recipes.remove(<modernmetals:manganese_bow>);
recipes.remove(<modernmetals:nichrome_bow>);
recipes.remove(<modernmetals:osmium_bow>);
recipes.remove(<modernmetals:plutonium_bow>);
recipes.remove(<modernmetals:rutile_bow>);
recipes.remove(<modernmetals:stainlesssteel_bow>);
recipes.remove(<modernmetals:tantalum_bow>);
recipes.remove(<modernmetals:titanium_bow>);
recipes.remove(<modernmetals:tungsten_bow>);
recipes.remove(<modernmetals:uranium_bow>);
recipes.remove(<modernmetals:zirconium_bow>);

mods.jei.JEI.hide(<modernmetals:aluminum_bow>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_bow>);
mods.jei.JEI.hide(<modernmetals:cadmium_bow>);
mods.jei.JEI.hide(<modernmetals:chromium_bow>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_bow>);
mods.jei.JEI.hide(<modernmetals:iridium_bow>);
mods.jei.JEI.hide(<modernmetals:magnesium_bow>);
mods.jei.JEI.hide(<modernmetals:manganese_bow>);
mods.jei.JEI.hide(<modernmetals:nichrome_bow>);
mods.jei.JEI.hide(<modernmetals:osmium_bow>);
mods.jei.JEI.hide(<modernmetals:plutonium_bow>);
mods.jei.JEI.hide(<modernmetals:rutile_bow>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_bow>);
mods.jei.JEI.hide(<modernmetals:tantalum_bow>);
mods.jei.JEI.hide(<modernmetals:titanium_bow>);
mods.jei.JEI.hide(<modernmetals:tungsten_bow>);
mods.jei.JEI.hide(<modernmetals:uranium_bow>);
mods.jei.JEI.hide(<modernmetals:zirconium_bow>);



// Arrows
recipes.remove(<modernmetals:aluminum_arrow>);
recipes.remove(<modernmetals:aluminumbrass_arrow>);
recipes.remove(<modernmetals:cadmium_arrow>);
recipes.remove(<modernmetals:chromium_arrow>);
recipes.remove(<modernmetals:galvanizedsteel_arrow>);
recipes.remove(<modernmetals:iridium_arrow>);
recipes.remove(<modernmetals:magnesium_arrow>);
recipes.remove(<modernmetals:manganese_arrow>);
recipes.remove(<modernmetals:nichrome_arrow>);
recipes.remove(<modernmetals:osmium_arrow>);
recipes.remove(<modernmetals:plutonium_arrow>);
recipes.remove(<modernmetals:rutile_arrow>);
recipes.remove(<modernmetals:stainlesssteel_arrow>);
recipes.remove(<modernmetals:tantalum_arrow>);
recipes.remove(<modernmetals:titanium_arrow>);
recipes.remove(<modernmetals:tungsten_arrow>);
recipes.remove(<modernmetals:uranium_arrow>);
recipes.remove(<modernmetals:zirconium_arrow>);

mods.jei.JEI.hide(<modernmetals:aluminum_arrow>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_arrow>);
mods.jei.JEI.hide(<modernmetals:cadmium_arrow>);
mods.jei.JEI.hide(<modernmetals:chromium_arrow>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_arrow>);
mods.jei.JEI.hide(<modernmetals:iridium_arrow>);
mods.jei.JEI.hide(<modernmetals:magnesium_arrow>);
mods.jei.JEI.hide(<modernmetals:manganese_arrow>);
mods.jei.JEI.hide(<modernmetals:nichrome_arrow>);
mods.jei.JEI.hide(<modernmetals:osmium_arrow>);
mods.jei.JEI.hide(<modernmetals:plutonium_arrow>);
mods.jei.JEI.hide(<modernmetals:rutile_arrow>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_arrow>);
mods.jei.JEI.hide(<modernmetals:tantalum_arrow>);
mods.jei.JEI.hide(<modernmetals:titanium_arrow>);
mods.jei.JEI.hide(<modernmetals:tungsten_arrow>);
mods.jei.JEI.hide(<modernmetals:uranium_arrow>);
mods.jei.JEI.hide(<modernmetals:zirconium_arrow>);



// Crossbow
recipes.remove(<modernmetals:aluminum_crossbow>);
recipes.remove(<modernmetals:aluminumbrass_crossbow>);
recipes.remove(<modernmetals:cadmium_crossbow>);
recipes.remove(<modernmetals:chromium_crossbow>);
recipes.remove(<modernmetals:galvanizedsteel_crossbow>);
recipes.remove(<modernmetals:iridium_crossbow>);
recipes.remove(<modernmetals:magnesium_crossbow>);
recipes.remove(<modernmetals:manganese_crossbow>);
recipes.remove(<modernmetals:nichrome_crossbow>);
recipes.remove(<modernmetals:osmium_crossbow>);
recipes.remove(<modernmetals:plutonium_crossbow>);
recipes.remove(<modernmetals:rutile_crossbow>);
recipes.remove(<modernmetals:stainlesssteel_crossbow>);
recipes.remove(<modernmetals:tantalum_crossbow>);
recipes.remove(<modernmetals:titanium_crossbow>);
recipes.remove(<modernmetals:tungsten_crossbow>);
recipes.remove(<modernmetals:uranium_crossbow>);
recipes.remove(<modernmetals:zirconium_crossbow>);

mods.jei.JEI.hide(<modernmetals:aluminum_crossbow>);
mods.jei.JEI.hide(<modernmetals:aluminumbrass_crossbow>);
mods.jei.JEI.hide(<modernmetals:cadmium_crossbow>);
mods.jei.JEI.hide(<modernmetals:chromium_crossbow>);
mods.jei.JEI.hide(<modernmetals:galvanizedsteel_crossbow>);
mods.jei.JEI.hide(<modernmetals:iridium_crossbow>);
mods.jei.JEI.hide(<modernmetals:magnesium_crossbow>);
mods.jei.JEI.hide(<modernmetals:manganese_crossbow>);
mods.jei.JEI.hide(<modernmetals:nichrome_crossbow>);
mods.jei.JEI.hide(<modernmetals:osmium_crossbow>);
mods.jei.JEI.hide(<modernmetals:plutonium_crossbow>);
mods.jei.JEI.hide(<modernmetals:rutile_crossbow>);
mods.jei.JEI.hide(<modernmetals:stainlesssteel_crossbow>);
mods.jei.JEI.hide(<modernmetals:tantalum_crossbow>);
mods.jei.JEI.hide(<modernmetals:titanium_crossbow>);
mods.jei.JEI.hide(<modernmetals:tungsten_crossbow>);
mods.jei.JEI.hide(<modernmetals:uranium_crossbow>);
mods.jei.JEI.hide(<modernmetals:zirconium_crossbow>);